print("="*10 + "Tabuada" + "="*10)
a = int(input("Insira um valor inteiro: "))
print("{} X 1 = {}".format(a, a*1))
print("{} X 2 = {}".format(a, a*2))
print("{} X 3 = {}".format(a, a*3))
print("{} X 4 = {}".format(a, a*4))
print("{} X 5 = {}".format(a, a*5))
print("{} X 6 = {}".format(a, a*6))
print("{} X 7 = {}".format(a, a*7))
print("{} X 8 = {}".format(a, a*8))
print("{} X 9 = {}".format(a, a*9))
print("{} X 10 = {}".format(a, a*10))
