print("Informações sobre o tipo")
a = input("Digite algo: ")
print("Alnum = {}".format(a.isalnum()))
print("Alpha = {}".format(a.isalpha()))
print("Decimal = {}".format(a.isdecimal()))
print("Digit = {}".format(a.isdigit()))
print("Identifier = {}".format(a.isidentifier()))
print("Slower = {}".format(a.islower()))
print("Numeric = {}".format(a.isnumeric()))
print("Printable = {}".format(a.isprintable()))
print("Space = {}".format(a.isspace()))
print("Title = {}".format(a.istitle()))
print("Upper = {}".format(a.isupper()))
